[workspace]

members = [
    "ubiart_toolkit",
    "jdmod",
    "dolphin_toolkit",
    "dotstar_toolkit_utils"
]

resolver = "2"

[profile.release]
debug = true
# overflow-checks = true

[profile.dev.package.aes]
opt-level = 3

[profile.dev.package.byteorder]
opt-level = 3

[profile.dev.package.cbc]
opt-level = 3

[profile.dev.package.cipher]
opt-level = 3

[profile.dev.package.clap]
opt-level = 3

[profile.dev.package.flate2]
opt-level = 3

[profile.dev.package.sha1]
opt-level = 3
