#cargo-features = ["codegen-backend"]
[workspace]

members = [
    "ubiart_toolkit",
    "jdmod",
    "wii_toolkit",
    "dotstar_toolkit_utils"
#, "rgbcx-sys", "rgbcx"
]

resolver = "2"

[profile.release]
debug = true

#[profile.dev]
#codegen-backend = "cranelift"
[profile.dev.package.ubiart_toolkit]
opt-level = 3
[profile.dev.package.dotstar_toolkit_utils]
opt-level = 3

[profile.dev.package."*"]
opt-level = 3

[workspace.lints.clippy]
all = "deny"
pedantic = "warn"
nursery = "warn"
cargo = "warn"
# If an integer doesn't fit it's a good indication that something broke
as_conversions = "deny"
empty_structs_with_brackets = "deny"
get_unwrap = "deny"
if_then_some_else_none = "deny"
lossy_float_literal = "deny"
missing_assert_message = "deny"
missing_panics_doc = "deny"
allow_attributes_without_reason = "deny"

[workspace.dependencies]
aes = { version = "0.8.4", default-features = false }
anyhow = { version = "1.0.81", default-features = false }
arbitrary = { version = "1.3.2", default-features = false }
bitflags = { version = "2.5.0", default-features = false }
bitvec = { version = "1.0.1", default-features = false }
byteorder = { version = "1.5.0", default-features = false }
cbc = { version = "0.1.2", default-features = false }
cipher = { version = "0.4.4", default-features = false }
clap = { version = "4.5.4", default-features = false }
crossbeam = { version = "0.8.4", default-features = false }
datatest-stable = "0.2.3"
flate2 = { version = "1.0.28", default-features = false }
hash32 = { version = "0.3.1", default-features = false }
image = { version = "0.25.1", default-features = false }
memmap2 = { version = "0.9.4", default-features = false }
nohash-hasher = { version = "0.2.0", default-features = false }
oxipng = { version = "9.0.0", default-features = false }
path-clean = { version = "1.0.1", default-features = false }
positioned-io = { version = "0.3.3", default-features = false }
quick-xml = { version = "0.31.0", default-features = false }
regex = { version = "1.10.4", default-features = false }
serde = { version = "1.0.197", default-features = false }
serde_json = { version = "1.0.115", default-features = false }
serde_with = { version = "3.7.0", default-features = false }
sha1 = { version = "0.10.6", default-features = false }
stable_deref_trait = { version = "1.2.0", default-features = false }
texpresso = { version = "2.0.1", default-features = false }
thiserror = { version = "1.0.58", default-features = false }
tracing = { version = "0.1.40", default-features = false }
ux = { version = "0.1.5", default-features = false }
yoke = { version = "0.7.3", default-features = false }
zopfli = { version = "0.8.0", default-features = false }
