[package]
name = "rgbcx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.4.1"
rgbcx-sys = { version = "0.1.0", path = "../rgbcx-sys" }

[lints]
workspace = true
