[package]
name = "ubiart_toolkit_shared_types"
version = "0.1.0"
edition = "2021"

[dependencies]
dotstar_toolkit_utils = { path = "../dotstar_toolkit_utils" }
quick-xml.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[lints]
workspace = true
