[package]
name = "xtx"
version = "0.1.0"
edition = "2021"

[dependencies]
dotstar_toolkit_utils = { version = "0.2.0", path = "../dotstar_toolkit_utils" }
image.workspace = true
tegra_swizzle.workspace = true
texpresso.workspace = true
thiserror.workspace = true

[lints]
workspace = true
